---
- name: Import LogDNA key
  ansible.builtin.rpm_key:
    state: present
    key: https://repo.logdna.com/logdna.gpg

- name: Add LogDNA repository
  yum_repository:
    name: logdna
    description: LogDNA packages
    baseurl: https://repo.logdna.com/el6/
    state: present
    enabled: yes
    gpgcheck: yes
    gpgkey: https://repo.logdna.com/logdna.gpg

- name: Install logdna-agent
  ansible.builtin.package:
    name: logdna-agent
    state: present

- name: Add API key to LogDNA
  ansible.builtin.command: logdna-agent -k 9746d2674c4d25b78ea2b74f9fa72490

- name: Startup LogDNA agent
  ansible.builtin.command: service logdna-agent start

- name: Enable LogDNA on system start
  ansible.builtin.command: chkconfig logdna-agent on