---
#? rsyslog__config_file:
#?   type: string
#?   description: Path to the rsyslogd configuration file.
#?   required: True
#?   default: /etc/rsyslog.conf
rsyslog__config_file: '/etc/rsyslog.conf'

#? rsyslog__confd_dir:
#?   type: string
#?   description: Path to the directory with all the additional configuration files for rsyslog.
#?   required: True
#?   default: /etc/rsyslog.d
rsyslog__confd_dir: '/etc/rsyslog.d'

#? rsyslog__package_name:
#?   type: string
#?   description: Install rsyslog software utility.
#?   required: True
#?   default: rsyslog
rsyslog__package_name: rsyslog

#? rsyslog__daemon_environment_file:
#?   type: string
#?   description: Path to the file with additional configuration for rsyslog daemon.
#?   required: True
#?   default: /etc/default/rsyslog
rsyslog__daemon_environment_file: '/etc/sysconfig/rsyslog'

#? rsyslog__remote_forward_port:
#?   type: integer
#?   description: Port of host to forward rsyslog events too.
#?   required: False
#?   default: 514
rsyslog__remote_forward_port: 514

#? rsyslog__remote_forward_host:
#?   type: string
#?   description: IP or fqdn of remote rsyslog host to forward events too.
#?   required: False
#?   default:
rsyslog__remote_forward_host:

#? rsyslog__remote_forwarding:
#?   type: boolean
#?   description: Set to true to enable config file setup for event forwarding.
#?   required: False
#?   default:
rsyslog__remote_forwarding:

#? rsyslog__remote_forward_protocol:
#?   type: string
#?   description: Protocol to use to forward events to the remote syslog server.
#?   required: False
#?   default: udp
rsyslog__remote_forward_protocol: udp