---
- name: Ensure rsyslog is installed
  yum: 
    name: "{{ rsyslog__package_name }}"
    state: present

- name: Deploy client config
  template:
    src: templates/rsyslog.conf7.j2
    dest: "{{ rsyslog__config_file }}"
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: syslog_conf_t
  notify: "Restart rsyslog"

- name: Ensure that rsyslog is running and enabled
  service:
    name: rsyslog
    state: started
    enabled: yes